//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hackaton
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShipmentsContainer : DbContext
    {
        public ShipmentsContainer()
            : base("name=ShipmentsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> CargoSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Transport> TransportSet { get; set; }
        public virtual DbSet<CargoAttribute> CargoAttributeSet { get; set; }
    }
}
